### ISSUE TITLE
AttributeError: module 'ctypes' has no attribute 'windll'

### ISSUE THREAD

**Issue by alleybeachelectric** [infinition/bjorn-detector#3]
**Describe the bug**
cannot run python3 bjorn-detector.py without getting this error:

io@Neptune bjorn-detector % python bjorn-detector.py 
Traceback (most recent call last):
  File "bjorn-detector.py", line 3, in <module>
    from src import main
ImportError: No module named src
io@Neptune bjorn-detector % 

**To Reproduce**
run through procedure on  M1 Max Macbook pro (MacOS 14.3 )

**Expected behavior**
to be able to run this on Mac,

**Screenshots**
<img width="397" alt="image" src="https://github.com/user-attachments/assets/d5222a94-975c-460f-baff-5f75f118bc8e">

**Additional context**

**Comment by JuanVilla424** [comment]
fixed.

https://github.com/JuanVilla424/bjorn-detector

**Comment by alleybeachelectric** [comment]
much thanks- still not being found on the network. Think that's my issue though 😛

**Comment by JuanVilla424** [comment]
try scan ur network using a network scan and identify bjorn IP address by hostname

**Comment by alleybeachelectric** [comment]
yea, not showing up- its a me issue lol.

**Comment by JuanVilla424** [comment]
Try this...


Hey Cybervikings ! 🤘🏻

I've noticed many of you are struggling with Bjorn "forgetting" its Wi-Fi networks whenever it connects to a new one... That's because of this f…..  "preconfigured" connection being a bit stubborn! 

While I work on an update to fix this properly, and integrate full WiFi's management with priorities and potfiles import, here's a quick temporary solution that'll make your life easier:

1️⃣ First, let's get rid of that annoying "preconfigured":

sudo nmcli connection delete "preconfigured"
sudo rm /etc/NetworkManager/system-connections/preconfigured.nmconnection



2️⃣ Then, you have two cool ways to add your networks:

The Easy Way (scanning and connecting):

# Scan available networks
nmcli device wifi list

# Connect to your network
nmcli device wifi connect "YourWiFiName" password "YourPassword"



The Pro Way (manual setup with priorities - higher number = higher priority):

First, create and edit your network configuration file:

sudo vi /etc/NetworkManager/system-connections/YourWiFiName.nmconnection



Add this configuration (replace YourWiFiName and YourPassword):

[connection]
id=HomeWiFi
type=wifi
autoconnect=true
autoconnect-priority=20

[wifi]
mode=infrastructure
ssid=YourWiFiName

[wifi-security]
auth-alg=open
key-mgmt=wpa-psk
psk=YourPassword

[ipv4]
method=auto

[ipv6]
method=auto



Finally, restart NetworkManager:

sudo systemctl restart NetworkManager



That's it! Now Bjorn will remember all your networks and automatically connect to the one with the highest priority when available.

Pro Tip: If you're using an iPhone hotspot, check "Maximize compatibility" option in your iPhone settings to force 2.4GHz connection if you're having issues.

Thanks to @infinition

**Comment by JuanVilla424** [comment]
solved #4
